statechange.cgi extended by return value "success"
homematic-community/XML-API pull request #78
Opened 2023-10-24 21:57 UTC by Maik2208

This solves tickes #74

2023-10-25 04:26 UTC, jens-maus requested changes
Sorry, but I think just adding the whole STDOUT to a nene xml attribute is too much. STDOUT is the verbatim return of a rega script call which could in principle also contain invalid chars not allowed in xml. Thus, this needs some preprocessing. 

Please explain which return values/codes you require and then revise your PR.

2023-10-25 06:37 UTC, Maik2208 commented
In all my tests STOUT had  only three different values:
Null if an invalid SID_ID was used, true if setting the value worked and false if it didn't worked because e.g. a text should be written into an Integer.
That is exactly what I would like to have returned. Did the value arrive in the variable or was there an error?

How can I force STOUT to contain other values besides changing the call in the source code?

Do you think it is safer if I always take "false" in the attribute in all cases where STOUT != "null" and != "true"?

2023-10-25 08:11 UTC, jens-maus commented
> How can I force STOUT to contain other values besides changing the call in the source code?

Well, in fact, you never know what might be the actual STDOUT result from tclrega.so in case there is a certain condition. So simply, play safe IMHO.
 
> Do you think it is safer if I always take "false" in the attribute in all cases where STOUT != "null" and != "true"?

Yes, please use an explicit check for the content of STDOUT and then just put `true` or `false` in the new `success` attribute.

2023-10-26 06:09 UTC, jens-maus approved these changes

2023-10-26 06:10 UTC, merged